import {defineArrayMember, defineField, defineType} from 'sanity'
const imageFields = [defineField({name: 'alt', title: 'Image description', type: 'string', validation: rule => rule.required()}), defineField({name: 'caption', type: 'string'}), defineField({name: 'credit', title: 'Photo credit', type: 'string'})]
export const activityType = defineType({
 name: 'activity', title: 'Pham workshops & activities', type: 'document',
 groups: [{name:'event',title:'Event',default:true},{name:'details',title:'Details & registration'},{name:'images',title:'Images'}],
 fields: [
  defineField({name:'contentType',title:'Content type',type:'string',group:'event',options:{list:[{title:'Workshop announcement',value:'announcement'},{title:'Workshop recap',value:'recap'}],layout:'radio'},initialValue:'announcement',validation:r=>r.required()}),
  defineField({name:'publishedAt',title:'Publication date',type:'datetime',group:'event',initialValue:()=>new Date().toISOString(),description:'Controls newest-first ordering on Pham. Event date controls the Year filter.',validation:r=>r.required()}),
  defineField({name:'relatedWorkshop',title:'Original workshop announcement',type:'reference',to:[{type:'activity'}],group:'event',hidden:({document})=>document?.contentType !== 'recap',options:{filter:'coalesce(contentType, "announcement") == "announcement"'},description:'Optional. Link this recap to its original invitation.'}),
  defineField({name:'title',title:'Activity title',type:'string',group:'event',validation:r=>r.required()}),
  defineField({name:'slug',type:'slug',group:'event',options:{source:'title'},validation:r=>r.required()}),
  defineField({name:'hidden',title:'Hide from website',type:'boolean',group:'event',initialValue:false}),
  defineField({name:'date',title:'Event date',type:'date',group:'event',validation:r=>r.required()}),
  defineField({name:'endDate',title:'End date (multi-day events)',type:'date',group:'event',validation:r=>r.min(r.valueOfField('date'))}),
  defineField({name:'time',hidden:({document})=>document?.contentType === 'recap',title:'Time (Thailand)',type:'string',group:'event',description:'Example: 08:30–18:30 (ICT)'}),
  defineField({name:'registrationStatus',hidden:({document})=>document?.contentType === 'recap',type:'string',group:'event',options:{list:['Open','Closed','Full','Past event']},initialValue:'Closed'}),
  defineField({name:'location',type:'string',group:'event'}),
  defineField({name:'mapUrl',title:'Map link',type:'url',group:'event'}),
  defineField({name:'summary',type:'text',rows:3,group:'event'}),
  defineField({name:'body',title:'Story / programme',type:'array',group:'details',of:[defineArrayMember({type:'block'})]}),
  defineField({name:'price',hidden:({document})=>document?.contentType === 'recap',title:'Price (THB per person)',type:'number',group:'details',validation:r=>r.min(0)}),
  defineField({name:'discount',hidden:({document})=>document?.contentType === 'recap',title:'Discount details',type:'string',group:'details'}),
  defineField({name:'minimumAge',hidden:({document})=>document?.contentType === 'recap',type:'number',group:'details',validation:r=>r.integer().min(0)}),
  defineField({name:'capacity',hidden:({document})=>document?.contentType === 'recap',type:'number',group:'details',validation:r=>r.integer().min(1)}),
  defineField({name:'registrationUrl',hidden:({document})=>document?.contentType === 'recap',title:'Registration form URL',type:'url',group:'details'}),
  defineField({name:'contactPhone',hidden:({document})=>document?.contentType === 'recap',type:'string',group:'details'}),
  defineField({name:'coverImage',title:'Cover / poster',type:'image',group:'images',options:{hotspot:true},fields:imageFields,description:'Use a poster for announcements or a photograph for recaps.',validation:r=>r.required().warning('Add a cover when available; the website supports a text-only event.')}),
  defineField({name:'gallery',title:'Photo gallery',type:'array',group:'images',of:[defineArrayMember({type:'image',options:{hotspot:true},fields:imageFields})]}),
 ],
 preview:{select:{title:'title',date:'date',contentType:'contentType',media:'coverImage'},prepare({title,date,contentType,media}){return {title,subtitle:`${contentType === 'recap' ? 'Recap' : 'Announcement'} · ${date || 'Date not set'}`,media}}},
 orderings:[{title:'Publication date (newest first)',name:'publishedDesc',by:[{field:'publishedAt',direction:'desc'}]}],
})
