import {defineArrayMember, defineField, defineType} from 'sanity'

export const projectType = defineType({
  name: 'project',
  title: 'Projects',
  type: 'document',
  groups: [
    {name: 'overview', title: 'Overview', default: true},
    {name: 'story', title: 'Project story'},
    {name: 'media', title: 'Images'},
    {name: 'credits', title: 'Recognition'},
  ],
  fields: [
    defineField({name: 'title', title: 'Project title', type: 'string', group: 'overview', validation: (rule) => rule.required()}),
    defineField({name: 'slug', title: 'URL slug', type: 'slug', group: 'overview', options: {source: 'title'}, validation: (rule) => rule.required()}),
    defineField({name: 'readyToPublish', title: 'Ready for publication', type: 'boolean', group: 'overview', initialValue: false}),
    defineField({name: 'sourceFingerprint', title: 'Source mapping fingerprint', type: 'string', group: 'media', readOnly: true, hidden: true}),
    defineField({name: 'sourceNumber', title: 'Source row number', type: 'number', group: 'overview'}),
    defineField({name: 'service', title: 'Service', type: 'string', group: 'overview', options: {list: ['Architect', 'Pavilion', 'Landscape', 'Renovation']}, validation: r => r.required()}),
    defineField({name: 'typologies', title: 'Typologies', type: 'array', group: 'overview', of: [defineArrayMember({type: 'string'})], options: {list: ['Residential', 'Office', 'Civic / Public', 'Heritage', 'Hospitality', 'Commercial', 'Culture', 'Nature / Recreation']}, validation: r => r.required().min(1)}),
    defineField({name: 'owner', title: 'Owner', type: 'string', group: 'credits'}),
    defineField({name: 'designCredit', title: 'Design credit', type: 'string', group: 'credits'}),
    defineField({name: 'completionLabel', title: 'Completion year / range', type: 'string', group: 'overview', description: 'For example 2025 – Present; follows the source Completion Year column.'}),
    defineField({name: 'photoSourceUrl', title: 'Source photo folder', type: 'url', group: 'media'}),
    defineField({name: 'awardText', title: 'Awards from project sheet', type: 'text', group: 'credits'}),
    defineField({name: 'featured', title: 'Show in selected works', type: 'boolean', group: 'overview', initialValue: true}),
    defineField({name: 'order', title: 'Display order', type: 'number', group: 'overview', initialValue: 10}),
    defineField({name: 'year', title: 'Year', type: 'number', group: 'overview'}),
    defineField({name: 'location', title: 'Location', type: 'string', group: 'overview'}),
    defineField({name: 'area', title: 'Size / area / length', type: 'string', group: 'overview', description: 'Example: 420 sq.m.'}),
    defineField({name: 'status', title: 'Project status', type: 'string', group: 'overview', options: {list: ['Completed', 'In progress', 'Concept']}}),
    defineField({name: 'materials', title: 'Materials', type: 'array', group: 'overview', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
    defineField({name: 'summary', title: 'Card summary', type: 'text', rows: 3, group: 'story', validation: (rule) => rule.max(240)}),
    defineField({name: 'description', title: 'Project description', type: 'array', group: 'story', of: [defineArrayMember({type: 'block'})]}),
    defineField({name: 'heroImage', title: 'Cover image', type: 'image', group: 'media', options: {hotspot: true}, fields: [defineField({name: 'sourceFileId', title: 'Drive file ID', type: 'string', readOnly: true}), defineField({name: 'sourceFilename', title: 'Original filename', type: 'string', readOnly: true}), defineField({name: 'alt', title: 'Alternative text', type: 'string', validation: (rule) => rule.required()})], validation: (rule) => rule.required()}),
    defineField({name: 'gallery', title: 'Gallery', type: 'array', group: 'media', of: [defineArrayMember({type: 'image', options: {hotspot: true}, fields: [defineField({name: 'sourceFileId', title: 'Drive file ID', type: 'string', readOnly: true}), defineField({name: 'sourceFilename', title: 'Original filename', type: 'string', readOnly: true}), defineField({name: 'alt', title: 'Alternative text', type: 'string'}), defineField({name: 'caption', title: 'Caption', type: 'string'})]})]}),
    defineField({name: 'awards', title: 'Awards', type: 'array', group: 'credits', of: [defineArrayMember({type: 'reference', to: [{type: 'recognition'}]})]}),
    defineField({name: 'pressUrl', title: 'Press or external reference', type: 'url', group: 'credits'}),
  ],
  preview: {
    select: {title: 'title', subtitle: 'location', media: 'heroImage'},
  },
})
